#pragma once
#define EE_HANDS
#define VIAL_KEYBOARD_UID {0x1a, 0x54, 0xd5, 0x60, 0x3e, 0xcf, 0x0a, 0x1f}
#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define PICO_FLASH_SIZE_BYTES (1 * 1024 * 1024)
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_ROTATION_270
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define POINTING_DEVICE_GESTURES_CURSOR_GLIDE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 0
#define POINTING_DEVICE_TASK_THROTTLE_MS 1
#define MOUSE_EXTENDED_REPORT
#define POINTING_DEVICE_DPI 12000
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE